<a href="https://colab.research.google.com/github/atharvadesai1/NLP-practice/blob/main/emailspam_BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sklearn
import pandas as pd

In [3]:
df = pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='ham' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     1
1         ham                      Ok lar... Joking wif u oni...     1
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     0
3         ham  U dun say so early hor... U c already then say...     1
4         ham  Nah I don't think he goes to usf, he lives aro...     1
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     0
5568      ham               Will ü b going to esplanade fr home?     1
5569      ham  Pity, * was in mood for that. So...any other s...     1
5570      ham  The guy did some bitching but I acted like i'd...     1
5571      ham                         Rofl. Its true to its name     1

[5572 rows x 3 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
 2   spam      5572 non-null   int64 
dtypes: int64(1), object(2)
memory usage: 130.7+ KB


In [7]:
df.shape

(5572, 3)

In [73]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)
x_train

3564    Auction round 4. The highest bid is now £54. N...
2609                            Hello madam how are you ?
5358    Hmm. Shall i bring a bottle of wine to keep us...
2627        Unni thank you dear for the recharge..Rakhesh
1657    Yes I posted a couple of pics on fb. There's s...
                              ...                        
4474                             S but not able to sleep.
1423    Congratulations ur awarded either £500 of CD g...
842     Pls send me a comprehensive mail about who i'm...
856     Talk sexy!! Make new friends or fall in love i...
328     I'd say that's a good sign but, well, you know...
Name: Message, Length: 4457, dtype: object

In [77]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train_cv = cv.fit_transform(x_train.values)
x_train_cv

<4457x7750 sparse matrix of type '<class 'numpy.int64'>'
	with 59021 stored elements in Compressed Sparse Row format>

In [78]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [79]:
x_train_cv.shape

(4457, 7750)

In [80]:
x_train_cv.ndim

2

In [81]:
x_train_cv.toarray()[0:2][1]

array([0, 0, 0, ..., 0, 0, 0])

In [82]:
cv.get_feature_names_out()[6093]

'shivratri'

In [83]:
x_train_cv_arr = x_train_cv.toarray()

In [84]:
x_train_cv_arr[0:5][0:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [85]:
np.where(x_train_cv_arr[0]!=0)

(array([ 258,  552,  608,  668, 1134, 1339, 1340, 3164, 3412, 3740, 4249,
        4396, 4768, 4839, 5821, 6003, 6814, 6932]),)

In [86]:
x_train[:][3564]

'Auction round 4. The highest bid is now £54. Next maximum bid is £71. To bid, send BIDS e. g. 10 (to bid £10) to 83383. Good luck.'

## **Training our Categories**

In [87]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [90]:
x_test_cv = cv.transform(x_test)

In [92]:
y_pred = model.predict(x_test_cv)
y_pred

array([1, 1, 0, ..., 1, 1, 1])

## **Evaluating performance**

In [94]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92       142
           1       0.99      0.99      0.99       973

    accuracy                           0.98      1115
   macro avg       0.96      0.95      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [95]:
confusion_matrix(y_test,y_pred)

array([[128,  14],
       [  8, 965]])